title: Khuyen Tran # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me 
  <br><br>
  My current mission
  <br><br>
  <a href="https://www.linkedin.com/in/khuyen-tran-1ab926151/">View My LinkedIn Profile</a> 
  <a href="https://github.com/khuyentran1401">View My Github Profile</a> 
  <a href="https://twitter.com/KhuyenTran16">View My Twitter</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
